###
Post http://localhost:3000/api/users
Content-Type: application/json



{
    "username": "newuser01",
    "password": "password01",
    "firstname": "New",
    "lastname": "User"
}

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "newuser02",
    "password": "pw02",
    "firstname": "user02",
    "lastname": "User02"
}

###
GET http://localhost:3000/api/roles

###
POST http://localhost:3000/api/roles
Content-Type: application/json

{
    "name": "Manager01",
    "description": "New Manager01"
}

###
PUT http://localhost:3000/api/roles/3
Content-Type: application/json

{
    "name": "Manager Updated",
    "description": "Updated Manager Role"
}

###
DELETE http://localhost:3000/api/roles/3



### Get all suppliers
GET http://localhost:3000/api/suppliers

### Create a new supplier
POST http://localhost:3000/api/suppliers
Content-Type: application/json

{
    "Name": "Phayao University",
    "Contact": "Aman Alikae",
    "Address": "Mueang Phayao, Phayao , Thailand,",
    "Email": "aman.aleekae@gmail.com",
    "Phone": "0945785806"
}

### Update supplier
PUT http://localhost:3000/api/suppliers/1
Content-Type: application/json

{
    "Name": "University of Phayao (Updated)",
    "Contact": "Jane Doe",
    "Address": "19 Moo 2, Tambon Mae Ka, Mueang Phayao, Phayao 56000, Thailand,",
    "Email": "67023086@up.ac.th",
    "Phone": "0811302829"
}

### Delete supplier
DELETE http://localhost:3000/api/suppliers/1
